### ISSUE TITLE
Error in seed.sql

### ISSUE THREAD

**Issue by monomelodies** [nickydevendt/myfirstsite#14]
psql:/home/monomelodies/sites/projects/sensi/myfirstsite/info/seed.sql:39: ERROR:  invalid input syntax for uuid: "abcdefghijklmnop123456"
LINE 3:         'abcdefghijklmnop123456',

**Comment by nickydevendt** [comment]
Dear Monomelodies,

When I search for pattern that contains UUID which is only used by the visitors table I cant find any insert that either contains uuid/UUID or the line that contains a uuid pattern. the only inserts currently in there are for users so one admin and one user and projects & affiliated company's.
Visitors are added throughout the users panel which is fast enough for testing.

Thank you for your contribution it is highly appreciated.

Nicky de Vendt
