### ISSUE TITLE
Use absolute URLs

### ISSUE THREAD

**Issue by monomelodies** [nickydevendt/myfirstsite#15]
E.g. <link href="./home.css">
This makes the path relative to the current path. By making URLs absolute (e.g. "/home.css", so w/o the leading dot) they are always relative to root. In that case, if you ever change /resume to /my/resume stuff will keep working.

**Comment by nickydevendt** [comment]
Dear Monomelodies,

I am not really sure with what you mean if I remove the leading dot stuff stops working like right now because __DIR__ looks into httpdocs so I need to the dot to return one folder..

greetings,
Nicky de Vendt

**Comment by nickydevendt** [comment]
thanks for the explanation Monomelodies all relative paths should be absolute now! :1st_place_medal:
